time_start: "20240701"
time_end: "20250101"
pairs: ['BTC/USDT:USDT']
run_policy:
  # - name: grid:inv  # 策略名称
  #   run_timeframes: [15m]  # 运行时间周期
  # params: {upperPrice: 50000, lowerPrice: 100000, gridNum: 20, initAmount: 100}
  - name: gridv2:ntgrid  # 策略名称
    run_timeframes: [1m]  # 运行时间周期
    params: {upperPrice: 100000 , lowerPrice: 50000, gridNum: 20, initAmount: 100}
accounts:
  user1:
    binance:
      prod:
        api_key: 
        api_secret: 
